name: Update

on:
  workflow_dispatch:

  push:
    branches: [ main ]
    paths:
      - CMIP6_downscaling_plans.csv
      - CORDEX_CMIP6_data_servers.yaml

jobs:
  update-tables:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment.yml

    - name: Update tables
      run: |
        which -a python
        conda activate test
        make update
       
    - name: Commit
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git commit -am "[Actions] Update"
        git push
