name: Update

on:
  workflow_dispatch:

  push:
    branches: [ main ]
    paths:
      - CMIP6_downscaling_plans.csv
  pull_request:
    branches: [ main ]
    paths:
      - CMIP6_downscaling_plans.csv

jobs:
  update-tables:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base

    - name: Update tables
      run: make update
       
    - name: Commit
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git commit -am "[Actions] Update"
        git push
